version: '3.8'
services:
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
    command: npm start
